# Generated by Django 5.2.13 on 2026-04-13 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_version', models.PositiveIntegerField()),
                ('crm_entity_type', models.CharField(max_length=20)),
                ('crm_entity_id', models.CharField(max_length=100)),
                ('filled_data', models.JSONField()),
                ('pdf_file', models.FileField(upload_to='contracts/%Y/%m/')),
                ('html_snapshot', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('viewed', 'Просмотрен'), ('signed', 'Подписан'), ('expired', 'Истёк'), ('cancelled', 'Отменён')], default='draft', max_length=20)),
                ('signing_method', models.CharField(choices=[('sms_otp', 'SMS-код'), ('email_otp', 'Email-код')], default='sms_otp', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signer_user_agent', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('html_body', models.TextField()),
                ('variable_schema', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_key', models.CharField(max_length=100)),
                ('crm_field_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SigningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('otp_code_hash', models.CharField(max_length=128)),
                ('otp_sent_to', models.CharField(max_length=200)),
                ('otp_sent_at', models.DateTimeField(auto_now_add=True)),
                ('otp_expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
            ],
        ),
    ]
