# Generated by Django 5.2.13 on 2026-04-14 18:26

from django.db import migrations, models


_COMMON_SCHEMA = [
    {'key': 'deal_id', 'sample': '42'},
    {'key': 'deal_name', 'sample': 'Тестовая сделка'},
    {'key': 'amount', 'sample': '100 000'},
    {'key': 'currency', 'sample': 'RUB'},
    {'key': 'contact_name', 'sample': 'Иванов И.И.'},
    {'key': 'company_name', 'sample': 'ООО «Пример»'},
]

SYSTEM_TEMPLATES = [
    {
        'name': 'Договор купли-продажи',
        'html_body': '<h1 style="text-align:center">Договор купли-продажи № {{ deal_id }}</h1>\n<p>г. ________________ &laquo;___&raquo; ____________ 20__ г.</p>\n<p><strong>Продавец:</strong> {{ company_name }}, в лице ________________, действующего на основании ________________,</p>\n<p><strong>Покупатель:</strong> {{ contact_name }},</p>\n<p>заключили настоящий Договор о нижеследующем:</p>\n<h2>1. Предмет договора</h2>\n<p>1.1. Продавец обязуется передать в собственность Покупателю, а Покупатель — принять и оплатить товар.</p>\n<p>1.2. Наименование сделки: {{ deal_name }}.</p>\n<h2>2. Цена и порядок расчётов</h2>\n<p>2.1. Стоимость товара составляет {{ amount }} {{ currency }}.</p>\n<p>2.2. Оплата производится в течение 5 банковских дней с момента подписания.</p>\n<h2>3. Ответственность сторон</h2>\n<p>3.1. За неисполнение обязательств стороны несут ответственность в соответствии с законодательством РФ.</p>\n<h2>4. Реквизиты и подписи сторон</h2>\n<table style="width:100%"><tr><td style="width:50%"><strong>Продавец</strong><br/>________________</td><td style="width:50%"><strong>Покупатель</strong><br/>________________</td></tr></table>',
    },
    {
        'name': 'Договор оказания услуг',
        'html_body': '<h1 style="text-align:center">Договор оказания услуг № {{ deal_id }}</h1>\n<p>г. ________________ &laquo;___&raquo; ____________ 20__ г.</p>\n<p><strong>Исполнитель:</strong> {{ company_name }}, в лице ________________, действующего на основании ________________,</p>\n<p><strong>Заказчик:</strong> {{ contact_name }},</p>\n<p>заключили настоящий Договор о нижеследующем:</p>\n<h2>1. Предмет договора</h2>\n<p>1.1. Исполнитель обязуется оказать Заказчику услуги, а Заказчик — принять и оплатить их.</p>\n<p>1.2. Описание: {{ deal_name }}.</p>\n<h2>2. Стоимость и порядок оплаты</h2>\n<p>2.1. Стоимость услуг составляет {{ amount }} {{ currency }}.</p>\n<p>2.2. Оплата — в течение 10 рабочих дней после подписания акта приёмки.</p>\n<h2>3. Сроки оказания услуг</h2>\n<p>3.1. Услуги оказываются в течение 30 календарных дней с момента подписания Договора.</p>\n<h2>4. Реквизиты и подписи сторон</h2>\n<table style="width:100%"><tr><td style="width:50%"><strong>Исполнитель</strong><br/>________________</td><td style="width:50%"><strong>Заказчик</strong><br/>________________</td></tr></table>',
    },
    {
        'name': 'Договор аренды',
        'html_body': '<h1 style="text-align:center">Договор аренды № {{ deal_id }}</h1>\n<p>г. ________________ &laquo;___&raquo; ____________ 20__ г.</p>\n<p><strong>Арендодатель:</strong> {{ company_name }}, в лице ________________, действующего на основании ________________,</p>\n<p><strong>Арендатор:</strong> {{ contact_name }},</p>\n<p>заключили настоящий Договор о нижеследующем:</p>\n<h2>1. Предмет договора</h2>\n<p>1.1. Арендодатель предоставляет Арендатору во временное пользование имущество.</p>\n<p>1.2. Описание: {{ deal_name }}.</p>\n<h2>2. Арендная плата</h2>\n<p>2.1. Ежемесячная арендная плата: {{ amount }} {{ currency }}.</p>\n<p>2.2. Оплата — не позднее 5-го числа текущего месяца.</p>\n<h2>3. Срок действия</h2>\n<p>3.1. Договор вступает в силу с момента подписания и действует 12 месяцев.</p>\n<h2>4. Реквизиты и подписи сторон</h2>\n<table style="width:100%"><tr><td style="width:50%"><strong>Арендодатель</strong><br/>________________</td><td style="width:50%"><strong>Арендатор</strong><br/>________________</td></tr></table>',
    },
]


def seed_system_templates(apps, schema_editor):
    ContractTemplate = apps.get_model('contracts', 'ContractTemplate')
    for tpl in SYSTEM_TEMPLATES:
        if not ContractTemplate.objects.filter(name=tpl['name'], is_system=True).exists():
            ContractTemplate.objects.create(
                name=tpl['name'],
                html_body=tpl['html_body'],
                variable_schema=_COMMON_SCHEMA,
                is_system=True,
                is_active=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(seed_system_templates, migrations.RunPython.noop),
    ]
