# Generated by Django 5.2.13 on 2026-04-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_add_is_system_and_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pdf_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of the PDF file at creation time', max_length=128),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature_data',
            field=models.JSONField(blank=True, help_text='Electronic signature details: hash, signer info, timestamp', null=True),
        ),
    ]
