# Generated by Django 5.2.13 on 2026-04-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_add_crypto_signature_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signingsession',
            name='otp_code_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
