# Generated by Django 5.2.15 on 2026-06-27 09:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('cancelled', 'Отменён'), ('refunded', 'Возврат')], default='pending', max_length=20)),
                ('months', models.PositiveIntegerField(default=1)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yookassa_payment_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('yookassa_confirmation_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_managers', models.PositiveIntegerField(blank=True, null=True)),
                ('max_documents_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('max_pipelines', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('max_messengers', models.PositiveIntegerField(blank=True, null=True)),
                ('max_inbound_channels', models.PositiveIntegerField(blank=True, null=True)),
                ('max_signatures_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('telephony_included', models.BooleanField(default=False)),
                ('max_phone_numbers', models.PositiveIntegerField(blank=True, null=True)),
                ('max_phone_lines', models.PositiveIntegerField(blank=True, null=True)),
                ('included_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('preset', 'Предустановленный'), ('custom', 'Конфигуратор')], default='preset', max_length=10)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PricingQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('config', models.JSONField(default=dict)),
                ('monthly_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('telephony_requires_quote', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelephonyQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('config_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('closed', 'Закрыта')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
