# Generated by Django 5.2.13 on 2026-04-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('max_managers', models.PositiveIntegerField(blank=True, null=True)),
                ('max_documents_per_month', models.PositiveIntegerField(blank=True, null=True)),
                ('max_crm_connections', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('max_pipelines', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('features', models.ManyToManyField(blank=True, related_name='plans', to='billing.feature')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
