# Generated by Django 5.2.13 on 2026-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='yookassa_confirmation_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='payment',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
