# Generated by Django 5.2.13 on 2026-04-13 17:34

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_type', models.CharField(choices=[('amocrm', 'amoCRM'), ('bitrix24', 'Битрикс24')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('credentials', apps.core.fields.EncryptedJSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('secret_token', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_user_id', models.CharField(blank=True, max_length=100)),
                ('crm_user_name', models.CharField(max_length=200)),
                ('max_active_deals', models.PositiveIntegerField(default=10)),
                ('schedule', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('crm_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='integrations.crmconnection')),
            ],
        ),
    ]
