# Generated by Django 5.2.13 on 2026-04-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmconnection',
            name='integration_mode',
            field=models.CharField(
                choices=[
                    ('webhook', 'Webhook / Manual'),
                    ('oauth', 'OAuth App'),
                    ('marketplace', 'Marketplace App'),
                ],
                default='webhook',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='crmconnection',
            name='last_health_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmconnection',
            name='last_webhook_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='last_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IntegrationErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('resolution', models.TextField(blank=True, default='')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='error', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crm_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='integrations.crmconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
