# Generated by Django 5.2.15 on 2026-06-17 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0003_connection_health_status_errorlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('html_body', models.TextField()),
                ('variable_schema', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Договор'), ('act', 'Акт'), ('invoice', 'Счёт'), ('offer', 'Оферта'), ('addendum', 'Дополнительное соглашение'), ('other', 'Прочее')], default='contract', max_length=20)),
                ('template_version', models.PositiveIntegerField()),
                ('crm_entity_type', models.CharField(max_length=20)),
                ('crm_entity_id', models.CharField(max_length=100)),
                ('filled_data', models.JSONField()),
                ('pdf_file', models.FileField(upload_to='documents/%Y/%m/')),
                ('html_snapshot', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('viewed', 'Просмотрен'), ('signed', 'Подписан'), ('expired', 'Истёк'), ('cancelled', 'Отменён')], default='draft', max_length=20)),
                ('signing_method', models.CharField(choices=[('sms_otp', 'SMS-код'), ('email_otp', 'Email-код')], default='sms_otp', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signer_user_agent', models.TextField(blank=True, default='')),
                ('pdf_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash of the PDF file at creation time', max_length=128)),
                ('signature_data', models.JSONField(blank=True, help_text='Electronic signature details: hash, signer info, timestamp', null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('crm_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.crmconnection')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_key', models.CharField(max_length=100)),
                ('crm_field_path', models.CharField(max_length=200)),
                ('crm_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.crmconnection')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='documents.documenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SigningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('otp_code_hash', models.CharField(blank=True, default='', max_length=128)),
                ('otp_sent_to', models.CharField(max_length=200)),
                ('otp_sent_at', models.DateTimeField(auto_now_add=True)),
                ('otp_expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_sessions', to='documents.document')),
            ],
        ),
    ]
