# Generated by Django 5.2.15 on 2026-06-17 11:57

from django.db import connection, migrations, models


def _seed_system_templates_for_current_schema(apps, schema_editor):
    """Seed templates only for the schema this migration is running on."""
    Tenant = apps.get_model('tenants', 'Tenant')
    tenant = Tenant.objects.get(schema_name=connection.schema_name)
    from apps.documents.seed import seed_system_templates_for_tenant
    seed_system_templates_for_tenant(tenant)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_deal_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(choices=[('contract', 'Договор'), ('act', 'Акт'), ('invoice', 'Счёт'), ('offer', 'Оферта'), ('addendum', 'Дополнительное соглашение'), ('other', 'Прочее')], default='contract', max_length=20),
        ),
        migrations.RunPython(
            code=_seed_system_templates_for_current_schema,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
