# Generated by Django 5.2.13 on 2026-04-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_signingtokenlookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
