# Generated by Django 5.2.13 on 2026-04-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_trial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='sip_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
