# Generated by Django 5.2.13 on 2026-04-13 17:34

import apps.core.fields
import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IVRMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('greeting_audio', models.FileField(blank=True, upload_to='telephony/ivr/')),
                ('greeting_tts', models.TextField(blank=True)),
                ('options', models.JSONField(default=list)),
                ('timeout', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('strategy', models.CharField(choices=[('ring_all', 'Звонок всем'), ('round_robin', 'По очереди'), ('least_recent', 'Наименее недавний'), ('random', 'Случайный')], default='ring_all', max_length=20)),
                ('ring_timeout', models.PositiveIntegerField(default=20)),
                ('max_wait_time', models.PositiveIntegerField(default=120)),
                ('hold_music', models.FileField(blank=True, upload_to='telephony/hold/')),
                ('announce_position', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(blank=True, related_name='call_queues', to='integrations.managerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SIPTrunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trunk_type', models.CharField(choices=[('zadarma', 'Zadarma'), ('mcn', 'MCN Telecom'), ('rostelecom', 'Ростелеком'), ('custom_sip', 'Произвольный SIP')], max_length=20)),
                ('credentials', apps.core.fields.EncryptedJSONField()),
                ('inbound_numbers', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('registering', 'Регистрация...'), ('error', 'Ошибка'), ('disabled', 'Отключён')], default='registering', max_length=20)),
                ('status_detail', models.TextField(blank=True)),
                ('last_registration_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crm_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sip_trunks', to='integrations.crmconnection')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=10)),
                ('sip_password', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('webrtc_enabled', models.BooleanField(default=True)),
                ('voicemail_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_extension', to='integrations.managerprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('extension',), name='unique_extension_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeswitch_uuid', models.CharField(max_length=200, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Входящий'), ('outbound', 'Исходящий'), ('internal', 'Внутренний')], max_length=10)),
                ('caller_number', models.CharField(max_length=50)),
                ('called_number', models.CharField(max_length=50)),
                ('result', models.CharField(choices=[('answered', 'Отвечен'), ('missed', 'Пропущен'), ('busy', 'Занято'), ('voicemail', 'Голосовая почта'), ('ivr_only', 'Только IVR')], max_length=20)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('wait_time', models.PositiveIntegerField(default=0)),
                ('crm_call_id', models.CharField(blank=True, max_length=200)),
                ('crm_contact_id', models.CharField(blank=True, max_length=100)),
                ('crm_lead_id', models.CharField(blank=True, max_length=100)),
                ('record_file', models.FileField(blank=True, upload_to='calls/%Y/%m/')),
                ('record_uploaded_to_crm', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='integrations.managerprofile')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telephony.callqueue')),
                ('sip_trunk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='telephony.siptrunk')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='telephony_c_started_ac1ef1_idx'), models.Index(fields=['caller_number'], name='telephony_c_caller__e3b477_idx'), models.Index(fields=['manager', '-started_at'], name='telephony_c_manager_bcf26f_idx')],
            },
        ),
    ]
