# Generated by Django 5.2.15 on 2026-06-27 09:36

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExolveChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exolve_number', models.CharField(blank=True, help_text='Номер в формате E.164, например 79991112233', max_length=20)),
                ('number_code', models.CharField(blank=True, help_text='number_code номера в Exolve', max_length=20)),
                ('type_id', models.PositiveIntegerField(blank=True, null=True)),
                ('region_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Не подключён'), ('connecting', 'Подключение…'), ('active', 'Активен'), ('error', 'Ошибка'), ('disabled', 'Отключён')], default='draft', max_length=20)),
                ('status_detail', models.TextField(blank=True)),
                ('forwarding_set_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=200, unique=True)),
                ('exolve_call_id', models.CharField(blank=True, max_length=64)),
                ('direction', models.CharField(choices=[('inbound', 'Входящий'), ('outbound', 'Исходящий'), ('internal', 'Внутренний')], max_length=10)),
                ('caller_number', models.CharField(max_length=50)),
                ('called_number', models.CharField(max_length=50)),
                ('result', models.CharField(choices=[('answered', 'Отвечен'), ('missed', 'Пропущен'), ('busy', 'Занято'), ('failed', 'Ошибка'), ('voicemail', 'Голосовая почта')], default='missed', max_length=20)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('wait_time', models.PositiveIntegerField(default=0)),
                ('talk_time', models.PositiveIntegerField(default=0)),
                ('cause_code', models.CharField(blank=True, max_length=10)),
                ('crm_call_id', models.CharField(blank=True, max_length=200)),
                ('crm_contact_id', models.CharField(blank=True, max_length=100)),
                ('crm_lead_id', models.CharField(blank=True, max_length=100)),
                ('record_file', models.FileField(blank=True, upload_to='calls/%Y/%m/')),
                ('record_uploaded_to_crm', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='team.manager')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CallTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Распознаётся'), ('done', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=12)),
                ('text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('provider', models.CharField(default='deepgram', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='telephony.callrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ExolveSIPAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sip_resource_id', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('password', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=200)),
                ('display_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('provisioning', 'Создаётся…'), ('active', 'Активен'), ('error', 'Ошибка'), ('disabled', 'Отключён')], default='provisioning', max_length=20)),
                ('status_detail', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exolve_sip', to='team.manager')),
            ],
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['-started_at'], name='telephony_c_started_ac1ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['caller_number'], name='telephony_c_caller__e3b477_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['manager', '-started_at'], name='telephony_c_manager_bcf26f_idx'),
        ),
        migrations.AddConstraint(
            model_name='exolvesipaccount',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_exolve_sip_username'),
        ),
    ]
