# Generated by Django 5.2.13 on 2026-04-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siptrunk',
            name='trunk_type',
            field=models.CharField(choices=[('zadarma', 'Zadarma'), ('mcn', 'MCN Telecom'), ('rostelecom', 'Ростелеком'), ('exolve', 'МТС Exolve'), ('custom_sip', 'Произвольный SIP')], max_length=20),
        ),
    ]
