# Generated by Django 5.2.15 on 2026-06-24 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0003_exolve'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Распознаётся'), ('done', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=12)),
                ('text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('provider', models.CharField(default='deepgram', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='telephony.callrecord')),
            ],
        ),
    ]
