# Generated by Django 5.2.14 on 2026-05-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rolepermission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='users_rolep_tenant__76808e_idx',
            old_name='users_rolep_tenant__58ac31_idx',
        ),
        migrations.RenameIndex(
            model_name='rolepermission',
            new_name='users_rolep_tenant__d35585_idx',
            old_name='users_rolep_tenant__7f689e_idx',
        ),
    ]
