# Generated by Django 5.2.15 on 2026-06-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rolepermission_index_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='entity',
            field=models.CharField(choices=[('deals', 'Deals'), ('contacts', 'Contacts'), ('companies', 'Companies'), ('products', 'Products')], max_length=20),
        ),
    ]
