# Generated by Django 5.2.15 on 2026-06-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_rolepermission_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='entity',
            field=models.CharField(choices=[('deals', 'Deals'), ('contacts', 'Contacts'), ('companies', 'Companies'), ('products', 'Products'), ('webforms', 'Web forms')], max_length=20),
        ),
    ]
