# Generated by Django 5.2.15 on 2026-06-27 09:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Звонок'), ('message', 'Сообщение'), ('task', 'Задача'), ('note', 'Заметка'), ('email', 'Email'), ('document', 'Документ'), ('stage_change', 'Смена стадии'), ('system', 'Системное')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('done', 'Выполнено'), ('overdue', 'Просрочено')], default='done', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('recurrence_rule', models.CharField(blank=True, max_length=300)),
                ('remind_at', models.DateTimeField(blank=True, help_text='Когда отправить напоминание ответственному (Celery-beat)', null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='Защита от повторной отправки напоминания', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('new_deal', 'Создана сделка'), ('stage_changed', 'Смена стадии'), ('no_activity', 'Нет активности N дней')], max_length=20)),
                ('conditions', models.JSONField(default=dict)),
                ('action', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('inn', models.CharField(blank=True, db_index=True, max_length=12)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('custom_fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('messenger_id', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('custom_fields', models.JSONField(default=dict)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('esign_agreement_signed_at', models.DateTimeField(blank=True, help_text='Дата подписания соглашения об использовании ЭП', null=True)),
                ('esign_agreement_id', models.PositiveIntegerField(blank=True, help_text='ID подписанного документа-соглашения об ЭП', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('loss_reason', models.CharField(blank=True, max_length=300)),
                ('custom_fields', models.JSONField(default=dict)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('contacts', 'Контакты'), ('companies', 'Компании')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('done', 'Завершён'), ('failed', 'Ошибка')], default='pending', max_length=10)),
                ('total', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('hour', 'час'), ('service', 'усл'), ('kg', 'кг'), ('month', 'мес'), ('license', 'лиц')], default='pcs', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(help_text='Первое число месяца плана')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Плановая сумма выручки за месяц (пусто = не задано)', max_digits=14, null=True)),
                ('target_count', models.PositiveIntegerField(blank=True, help_text='Плановое число выигранных сделок за месяц (пусто = не задано)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_month'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('entity', models.CharField(choices=[('contacts', 'Контакты'), ('deals', 'Сделки')], default='contacts', max_length=20)),
                ('filters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stage_type', models.CharField(choices=[('open', 'В работе'), ('won', 'Успешно завершена'), ('lost', 'Проиграна')], default='open', max_length=10)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('auto_action', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='#6366F1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('fields_schema', models.JSONField(default=list)),
                ('source', models.CharField(default='webform', max_length=50)),
                ('auto_distribute', models.BooleanField(default=True)),
                ('success_message', models.CharField(default='Спасибо! Мы свяжемся с вами.', max_length=300)),
                ('allowed_origins', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('submissions_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
