# Generated by Django 5.2.15 on 2026-06-27 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('documents', '0001_initial'),
        ('messenger_channels', '0001_initial'),
        ('telephony', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='related_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='telephony.callrecord'),
        ),
        migrations.AddField(
            model_name='activity',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='documents.document'),
        ),
        migrations.AddField(
            model_name='activity',
            name='related_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='messenger_channels.messagelog'),
        ),
        migrations.AddField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationrunlog',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='crm.automationrule'),
        ),
        migrations.AddField(
            model_name='company',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.company'),
        ),
        migrations.AddField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='deal',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationrunlog',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='activity',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='dealitem',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='dealitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_items', to='crm.product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crm.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='crm.productcategory'),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='pipeline',
            field=models.ForeignKey(blank=True, help_text='Воронка плана; пусто = по всем воронкам', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='salestarget',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Менеджер плана; пусто = командная цель', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stage',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.stage'),
        ),
        migrations.AddField(
            model_name='stagetransition',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='stagetransition',
            name='from_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_out', to='crm.stage'),
        ),
        migrations.AddField(
            model_name='stagetransition',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='stagetransition',
            name='to_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_in', to='crm.stage'),
        ),
        migrations.AddField(
            model_name='tag',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='tags', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='tag',
            name='deals',
            field=models.ManyToManyField(blank=True, related_name='tags', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='webform',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webforms', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='webform',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webforms', to='crm.stage'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='crm_contact_phone_189db8_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='crm_contact_email_240305_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrunlog',
            index=models.Index(fields=['rule', 'deal'], name='crm_automat_rule_id_20b629_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='automationrunlog',
            unique_together={('rule', 'deal')},
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['deal', '-created_at'], name='crm_activit_deal_id_bf5adf_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['contact', '-created_at'], name='crm_activit_contact_63bbb4_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['responsible', 'status', '-due_date'], name='crm_activit_respons_2e2b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status', 'remind_at'], name='crm_activit_status_973d01_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='crm_product_sku_f90e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'name'], name='crm_product_is_acti_13b95e_idx'),
        ),
        migrations.AddConstraint(
            model_name='salestarget',
            constraint=models.UniqueConstraint(fields=('period_month', 'responsible', 'pipeline'), name='uniq_sales_target_month_manager_pipeline', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['stage', '-updated_at'], name='crm_deal_stage_i_27ba3b_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['responsible', '-updated_at'], name='crm_deal_respons_11d868_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['contact'], name='crm_deal_contact_c2c81d_idx'),
        ),
        migrations.AddIndex(
            model_name='stagetransition',
            index=models.Index(fields=['pipeline', 'to_stage'], name='crm_stagetr_pipelin_2f0403_idx'),
        ),
        migrations.AddIndex(
            model_name='stagetransition',
            index=models.Index(fields=['deal', 'created_at'], name='crm_stagetr_deal_id_4577b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name',), name='uniq_tag_name'),
        ),
    ]
