# Generated by Django 5.2.13 on 2026-04-13 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
        ('crm', '0001_initial'),
        ('integrations', '0001_initial'),
        ('messenger_channels', '0001_initial'),
        ('telephony', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='related_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='telephony.callrecord'),
        ),
        migrations.AddField(
            model_name='activity',
            name='related_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='activity',
            name='related_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='messenger_channels.messagelog'),
        ),
        migrations.AddField(
            model_name='activity',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='integrations.managerprofile'),
        ),
        migrations.AddField(
            model_name='company',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='integrations.managerprofile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='integrations.managerprofile'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.company'),
        ),
        migrations.AddField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='deal',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='integrations.managerprofile'),
        ),
        migrations.AddField(
            model_name='activity',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='deal',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='stage',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.stage'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='crm_contact_phone_189db8_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='crm_contact_email_240305_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['deal', '-created_at'], name='crm_activit_deal_id_bf5adf_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['contact', '-created_at'], name='crm_activit_contact_63bbb4_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['responsible', 'status', '-due_date'], name='crm_activit_respons_2e2b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['stage', '-updated_at'], name='crm_deal_stage_i_27ba3b_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['responsible', '-updated_at'], name='crm_deal_respons_11d868_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['contact'], name='crm_deal_contact_c2c81d_idx'),
        ),
    ]
