# Generated by Django 5.2.13 on 2026-04-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_responsible_to_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activity',
            new_name='crm_activit_respons_2e2b4f_idx',
            old_name='crm_activit_respons_user_idx',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='crm_deal_respons_11d868_idx',
            old_name='crm_deal_respons_user_idx',
        ),
    ]
