# Generated by Django 5.2.13 on 2026-04-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_crm_activit_respons_user_idx_crm_activit_respons_2e2b4f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='esign_agreement_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID подписанного договора-соглашения об ЭП', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='esign_agreement_signed_at',
            field=models.DateTimeField(blank=True, help_text='Дата подписания соглашения об использовании ЭП', null=True),
        ),
    ]
