# Generated by Django 5.2.15 on 2026-06-21 19:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_product_dealitem_productcategory_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('fields_schema', models.JSONField(default=list)),
                ('source', models.CharField(default='webform', max_length=50)),
                ('auto_distribute', models.BooleanField(default=True)),
                ('success_message', models.CharField(default='Спасибо! Мы свяжемся с вами.', max_length=300)),
                ('allowed_origins', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('submissions_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webforms', to='crm.pipeline')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webforms', to='crm.stage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
