# Generated by Django 5.2.15 on 2026-06-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_webform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('entity', models.CharField(choices=[('contacts', 'Контакты'), ('deals', 'Сделки')], default='contacts', max_length=20)),
                ('filters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='#6366F1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='tags', to='crm.contact')),
                ('deals', models.ManyToManyField(blank=True, related_name='tags', to='crm.deal')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_tag_name')],
            },
        ),
    ]
