# Generated by Django 5.2.15 on 2026-06-21 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_segment_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('new_deal', 'Создана сделка'), ('stage_changed', 'Смена стадии'), ('no_activity', 'Нет активности N дней')], max_length=20)),
                ('conditions', models.JSONField(default=dict)),
                ('action', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to='crm.deal')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='crm.automationrule')),
            ],
            options={
                'indexes': [models.Index(fields=['rule', 'deal'], name='crm_automat_rule_id_20b629_idx')],
                'unique_together': {('rule', 'deal')},
            },
        ),
    ]
