# Generated by Django 5.2.15 on 2026-06-22 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_importjob'),
        ('documents', '0003_documenttemplate_document_type'),
        ('messenger_channels', '0003_alter_messengerchannel_channel_type'),
        ('telephony', '0003_exolve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='activity',
            name='remind_at',
            field=models.DateTimeField(blank=True, help_text='Когда отправить напоминание ответственному (Celery-beat)', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Защита от повторной отправки напоминания', null=True),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status', 'remind_at'], name='crm_activit_status_973d01_idx'),
        ),
    ]
