# Generated by Django 5.2.15 on 2026-06-22 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_activity_recurrence_rule_activity_remind_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(help_text='Первое число месяца плана')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Плановая сумма выручки за месяц (пусто = не задано)', max_digits=14, null=True)),
                ('target_count', models.PositiveIntegerField(blank=True, help_text='Плановое число выигранных сделок за месяц (пусто = не задано)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_month'],
                'constraints': [models.UniqueConstraint(fields=('period_month', 'responsible'), name='uniq_sales_target_month_manager')],
            },
        ),
    ]
