# Generated by Django 5.2.13 on 2026-04-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_entity_type', models.CharField(max_length=20)),
                ('crm_entity_id', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('crm_webhook', 'CRM-вебхук'), ('messenger', 'Мессенджер'), ('phone_call', 'Телефонный звонок'), ('manual', 'Ручное')], default='crm_webhook', max_length=20)),
                ('strategy_used', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistributionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('new_lead', 'Новая заявка'), ('new_deal', 'Новая сделка'), ('stage_change', 'Смена стадии')], max_length=20)),
                ('trigger_filter', models.JSONField(default=dict)),
                ('strategy', models.CharField(choices=[('min_load', 'Минимальная нагрузка'), ('round_robin', 'По очереди'), ('weighted', 'Взвешенное'), ('manual_queue', 'Ручная очередь')], default='min_load', max_length=20)),
                ('strategy_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
