# Generated by Django 5.2.15 on 2026-06-27 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionlog',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.manager'),
        ),
        migrations.AddField(
            model_name='distributionrule',
            name='fallback_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_rules', to='team.manager'),
        ),
        migrations.AddField(
            model_name='distributionrule',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='distribution_rules', to='team.manager'),
        ),
        migrations.AddField(
            model_name='distributionlog',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribution.distributionrule'),
        ),
    ]
