# Generated by Django 5.2.13 on 2026-04-13 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionlog',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.managerprofile'),
        ),
        migrations.AddField(
            model_name='distributionlog',
            name='crm_connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.crmconnection'),
        ),
        migrations.AddField(
            model_name='distributionrule',
            name='crm_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.crmconnection'),
        ),
        migrations.AddField(
            model_name='distributionrule',
            name='fallback_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_rules', to='integrations.managerprofile'),
        ),
        migrations.AddField(
            model_name='distributionrule',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='distribution_rules', to='integrations.managerprofile'),
        ),
        migrations.AddField(
            model_name='distributionlog',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribution.distributionrule'),
        ),
    ]
