# Generated by Django 5.2.14 on 2026-05-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionlog',
            name='source',
            field=models.CharField(choices=[('builtin_crm', 'Встроенная CRM'), ('crm_webhook', 'CRM-вебхук'), ('messenger', 'Мессенджер'), ('phone_call', 'Телефонный звонок'), ('manual', 'Ручное')], default='crm_webhook', max_length=20),
        ),
        migrations.AlterField(
            model_name='distributionrule',
            name='trigger',
            field=models.CharField(choices=[('new_deal', 'Новая сделка')], max_length=20),
        ),
    ]
