# Generated by Django 5.2.13 on 2026-04-13 17:34

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_chat_id', models.CharField(max_length=200)),
                ('external_user_name', models.CharField(blank=True, max_length=200)),
                ('crm_contact_id', models.CharField(blank=True, max_length=100)),
                ('crm_chat_id', models.CharField(blank=True, max_length=200)),
                ('crm_lead_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Входящее'), ('out', 'Исходящее')], max_length=3)),
                ('text', models.TextField(blank=True)),
                ('attachments', models.JSONField(default=list)),
                ('external_message_id', models.CharField(blank=True, max_length=200)),
                ('crm_message_id', models.CharField(blank=True, max_length=200)),
                ('delivered', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger_channels.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessengerChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel_type', models.CharField(choices=[('telegram', 'Telegram Bot'), ('whatsapp_business', 'WhatsApp Business API'), ('whatsapp', 'WhatsApp (через провайдера)'), ('max', 'MAX')], max_length=20)),
                ('credentials', apps.core.fields.EncryptedJSONField()),
                ('crm_channel_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('error', 'Ошибка'), ('disabled', 'Отключён')], default='active', max_length=20)),
                ('status_detail', models.TextField(blank=True)),
                ('auto_create_lead', models.BooleanField(default=True)),
                ('welcome_message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crm_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_channels', to='integrations.crmconnection')),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='messenger_channels.messengerchannel'),
        ),
        migrations.AlterUniqueTogether(
            name='chatsession',
            unique_together={('channel', 'external_chat_id')},
        ),
    ]
