# Generated by Django 5.2.15 on 2026-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_channels', '0002_messengerchannel_vk_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messengerchannel',
            name='channel_type',
            field=models.CharField(choices=[('telegram', 'Telegram Bot'), ('whatsapp_business', 'WhatsApp Business API'), ('whatsapp', 'WhatsApp (через провайдера)'), ('max', 'MAX'), ('vk', 'ВКонтакте'), ('email', 'Электронная почта')], max_length=20),
        ),
    ]
