# Generated by Django 5.2.13 on 2026-04-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('contract_signed', 'Договор подписан'), ('lead_distributed', 'Заявка распределена'), ('crm_connection_lost', 'CRM-соединение потеряно'), ('crm_connection_restored', 'CRM-соединение восстановлено'), ('plan_limit_warning', 'Лимит плана на исходе (80%)'), ('plan_limit_reached', 'Лимит плана достигнут'), ('user_invited', 'Пользователь приглашён'), ('manager_sync_done', 'Синхронизация менеджеров завершена'), ('signing_expired', 'Срок подписания истёк'), ('deal_stage_changed', 'Сделка перемещена'), ('task_overdue', 'Задача просрочена'), ('new_deal_created', 'Новая сделка создана')], max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('telegram', 'Telegram')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('contract_signed', 'Договор подписан'), ('lead_distributed', 'Заявка распределена'), ('crm_connection_lost', 'CRM-соединение потеряно'), ('crm_connection_restored', 'CRM-соединение восстановлено'), ('plan_limit_warning', 'Лимит плана на исходе (80%)'), ('plan_limit_reached', 'Лимит плана достигнут'), ('user_invited', 'Пользователь приглашён'), ('manager_sync_done', 'Синхронизация менеджеров завершена'), ('signing_expired', 'Срок подписания истёк'), ('deal_stage_changed', 'Сделка перемещена'), ('task_overdue', 'Задача просрочена'), ('new_deal_created', 'Новая сделка создана')], max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('telegram', 'Telegram')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('recipient_roles', models.JSONField(default=list, help_text='["owner", "admin", "manager"] — пустой список = owner+admin')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
