# Generated by Django 5.2.15 on 2026-06-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('document_signed', 'Документ подписан'), ('lead_distributed', 'Заявка распределена'), ('crm_connection_lost', 'CRM-соединение потеряно'), ('crm_connection_restored', 'CRM-соединение восстановлено'), ('plan_limit_warning', 'Лимит плана на исходе (80%)'), ('plan_limit_reached', 'Лимит плана достигнут'), ('user_invited', 'Пользователь приглашён'), ('manager_sync_done', 'Синхронизация менеджеров завершена'), ('signing_expired', 'Срок подписания истёк'), ('deal_stage_changed', 'Сделка перемещена'), ('task_overdue', 'Задача просрочена'), ('task_reminder', 'Напоминание о задаче'), ('new_deal_created', 'Новая сделка создана')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event',
            field=models.CharField(choices=[('document_signed', 'Документ подписан'), ('lead_distributed', 'Заявка распределена'), ('crm_connection_lost', 'CRM-соединение потеряно'), ('crm_connection_restored', 'CRM-соединение восстановлено'), ('plan_limit_warning', 'Лимит плана на исходе (80%)'), ('plan_limit_reached', 'Лимит плана достигнут'), ('user_invited', 'Пользователь приглашён'), ('manager_sync_done', 'Синхронизация менеджеров завершена'), ('signing_expired', 'Срок подписания истёк'), ('deal_stage_changed', 'Сделка перемещена'), ('task_overdue', 'Задача просрочена'), ('task_reminder', 'Напоминание о задаче'), ('new_deal_created', 'Новая сделка создана')], max_length=50),
        ),
    ]
